version: '2.18.1'

services:
  Registry-Service:
    image: swa/registry-service:latest
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - swa-project-network

  Config-Server:
    image: swa/config-server:latest
    expose:
      - "8888"
    ports:
      - "8888:8888"
    networks:
      - swa-project-network
    links:
      - Registry-Service
    depends_on:
      - Registry-Service
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://config-service:8888" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
    environment:
      EUREKA_HOST: Registry-Service
#      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://Registry-Service:8761/eureka

  Api-Gateway:
    image: swa/api-gateway:latest
    restart: always
    expose:
      - "8081"
    ports:
      - "8081:8081"
    networks:
      - swa-project-network
    links:
      - Config-Server
      - Registry-Service
    depends_on:
      - Config-Server
      - Registry-Service
    environment:
      CONFIG_HOST: Config-Server
      EUREKA_HOST: Registry-Service
#      SPRING.CONFIG.IMPORT: optional:configserver:http://Config-Server:8888
#      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://Registry-Service:8761/eureka

  code-supplier-service:
    image: swa/code-supplier-service:latest
    restart: always
    expose:
      - "8085"
    ports:
      - "8085:8085"
    networks:
      - swa-project-network
    links:
      - Config-Server
      - Registry-Service
    depends_on:
      - Config-Server
      - Registry-Service
    environment:
      CONFIG_HOST: Config-Server
      EUREKA_HOST: Registry-Service
#      SPRING.CONFIG.IMPORT: optional:configserver:http://Config-Server:8888
#      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://Registry-Service:8761/eureka


networks:
  swa-project-network:
    driver: bridge