version: '2.18.1'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  Registry-Service:
    image: swa/registry-service:latest
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - swa-project-network

  Config-Server:
    image: swa/config-server:latest
    expose:
      - "8888"
    ports:
      - "8888:8888"
    networks:
      - swa-project-network
    links:
      - Registry-Service
    depends_on:
      - Registry-Service
    environment:
      EUREKA_HOST: Registry-Service

  Api-Gateway:
    image: swa/api-gateway:latest
    restart: always
    expose:
      - "8081"
    ports:
      - "8081:8081"
    networks:
      - swa-project-network
    links:
      - Config-Server
      - Registry-Service
    depends_on:
      - Config-Server
      - Registry-Service
    environment:
      CONFIG_HOST: Config-Server
      EUREKA_HOST: Registry-Service

  code-supplier-service:
    image: swa/code-supplier-service:latest
    restart: always
    expose:
      - "8085"
    ports:
      - "8085:8085"
    networks:
      - swa-project-network
    links:
      - Config-Server
      - Registry-Service
    depends_on:
      - Config-Server
      - Registry-Service
    environment:
      CONFIG_HOST: Config-Server
      EUREKA_HOST: Registry-Service

  WDFS_Service:
    image: swa/wdfs-service:latest
    expose:
      - "8901"
    ports:
      - "8901:8901"
    links:
      - kafka
    depends_on:
      - kafka

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db

  reporting-service:
    image: swa/reporting-service:latest
    restart: always
    expose:
      - "8385"
    ports:
      - "8385:8385"
    networks:
      - swa-project-network
    links:
      - Config-Server
      - Registry-Service
    depends_on:
      - Config-Server
      - Registry-Service
      - mongodb
      - kafka
    environment:
      CONFIG_HOST: Config-Server
      EUREKA_HOST: Registry-Service
      MONGO_HOST: mongodb
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafka:29092

networks:
  swa-project-network:
    driver: bridge